rose/accounts/urls.py
from django.conf.urls.defaults import *
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from accounts import views as userena_views
from accounts import settings as userena_settings

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup/$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       {'template_name': 'userena/password_reset_form.html',
        'email_template_name': 'userena/emails/password_reset_message.txt'},
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html'},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
       auth_views.password_reset_confirm,
       {'template_name': 'userena/password_reset_confirm_form.html'},
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'}),

   

    # Activate
    url(r'^activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w]+)/disabled/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),
    # pyynnot profile
    url(r'^(?P<username>[\.\w]+)/pyynnot/$',
       userena_views.profile_pyynnot,
       name='userena_profile_pyynnot'),
    url(r'^(?P<username>[\.\w]+)/tyopaikat/$',
       userena_views.tyopaikat,
       name='userena_tyopaikat'),
    url(r'^(?P<username>[\.\w]+)/tyopaikat/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/tyopaikka_complete.html'},
       name='userena_tyopaikat_complete'),
    url(r'^(?P<username>[\.\w]+)/tyopaikat/details/$',
       userena_views.tyopaikat_detail,
       {'template_name': 'userena/tyopaikka_detail.html'},
       name='userena_tyopaikat_detail'),
    url(r'^(?P<username>[\.\w]+)/tyopaikat/delete/(?P<id>[\.\w]+)/$',
       userena_views.delete_tp,
#       {'template_name': 'userena/delete_tp.html'},
       
       name='userena_delete_tp'),
    url(r'^(?P<username>[\.\w]+)/tyopaikat/deletecomplete/$',  
	userena_views.direct_to_user_template,
	{'template_name': 'userena/delete_tp.html'},
	name='userena_deletecomplete'),
  
 # Signup
    url(r'^(?P<username>[\.\w]+)/signup/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/signup_complete.html',
        'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
                          'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
       name='userena_signup_complete'),
    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

rose/rose/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from accounts.forms import SignupFormExtra
from accounts.models import TarjousModelFormPreview
from tarjoukset.models import TarjousModelForm
from django import forms
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rose.views.home', name='home'),
    # url(r'^rose/', include('rose.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^asiakastarjoukset/', include('asiakastarjoukset.urls')),
    url(r'^tarjoukset/', include('tarjoukset.urls')),
  #  (r'^accounts/', include('rekisterointi.urls')),
    url(r'^postman/',include('postman.urls')),
    (r'^forms/', include('form_designer.urls')),
    (r'^contact/', include('contact_form.urls')),
    #(r'^contacts/', 'contacts.views.main'),
 #   (r'^accounts/None/signup/complete
    (r'^accounts/signup/$',
     'accounts.views.signup',
     {'signup_form': SignupFormExtra}),
 
    (r'^post/$', TarjousModelFormPreview(TarjousModelForm)),
    (r'^tyopaikat/', include('tyopaikat.urls')),
    (r'^accounts/', include('accounts.urls')),
    url(r'^toimialakategoriat/', include('toimialakategoriat.urls')),
    
      # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
  
     url(r'^', include('cms.urls')),
#	(r'','rainbow.views.index'),
)
if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

rose/contacts/models.py
from django.db import models
from django.forms import ModelForm
# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)

    def __unicode__(self):
	return self.name

class ContactForm(ModelForm):
    class Meta:
	model = Contact

rose/templates/base.html
{% load menu_tags cache %}
{% load i18n cms_tags menu_tags%}
{% load cms_tags sekizai_tags %}
{% load sekizai_tags %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
      {% render_block "css" %}
{% addtoblock "css" %}
<link href="{{STATIC_URL}}css/style.css?{% now "U" %}" rel="stylesheet" type="text/css"/>
<link href="{{STATIC_URL}}js/css/pepper-grinder/jquery-ui-1.8.23.custom.css" rel="stylesheet" type="text/css"/>
<link href="http://fonts.googleapis.com/css?family=Abel" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" media="all" href="{{STATIC_URL}}css/niceforms-default.css" />
{%endaddtoblock%} 
{% render_block "js" %}
  </head>
  <body>
      {% cms_toolbar %}
  
      
	{% addtoblock "js" %}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
   <script type="text/javascript" src="{{STATIC_URL}}js/js/jquery-ui-1.8.23.custom.min.js"></script>
   <script type="text/javascript" src="{{STATIC_URL}}js/js/jquery-ui-fi.js"></script>

 <script type="text/javascript" src="{{STATIC_URL}}js/js/jquery.dropotron-1.0.js"></script>
<script language="javascript" type="text/javascript" src="{{STATIC_URL}}js/js/niceforms.js"></script>
<script>
	$(function() {
		$( "#id_tarjoukset_viimeistaan" ).datepicker();
		$( "#id_haku_viimeistaan" ).datepicker();
	});
	</script>

{%endaddtoblock%} 
<div id ="wrapper">

	<div id="header-wrapper">

		<div id="header">
			<div id="logo">
			
			</div>
		</div>
	
	</div>
	<!-- end #header -->
	<div id="menu-wrapper">
		<ul id="menu"><span>
			 {% show_menu 0 100 100 100 %}
			</span>
			
			<li><a href="#"><span>ketä ollaan</span></a></li>
			<li><a href="/tarjoukset" target="_self"><span>Jätä tarjouspyyntö!</span></a> </li>
			
			<li><a href="/tyopaikat/tyopaikat_haku" target="_self"><span>Avoimet työpaikat</span></a> </li>
			<li><a href="/tarjoukset/selaa"><span>Selaa tarjouspyyntöjä</span></a></li>
			<li><span>Yrityksille</span>
				<ul>
					<li class="first"> <a href="/accounts/signin/" target="_self">Kirjaudu</a>  </li>
					<li class="last"> <a href="/accounts/signup/" target="_self">Rekisteröidy</a>  </li>
					
					<li class="last"> <a href="#" target="_self">Miten homma toimii</a>  </li>
				</ul>
			</li>
		</ul>

		<script type="text/javascript">
			$('#menu').dropotron();
		</script>
	</div>
	<!-- end #menu -->
	<div id="splash"><img src="images/pics01.jpg" width="980" height="300" alt="" /></div>
	<div id="page">
		<div id="content">
			<div class="contentbg">
				<div class="post">
					<div class="entry">
						 {% placeholder content %}
      {% block content%}{% endblock %}
					</div>
				</div>
				
			</div>
		</div>
		<!-- end #content -->
		<div id="sidebar-bg">
			<div id="sidebar">
				<ul>
					<li>
						 {% placeholder sivusisalto %}
     						 {% block sivusisalto%}{% endblock %}
					</li>
					<li>
						 {% placeholder sivusisalto2 %}
     						 {% block sivusisalto2%}{% endblock %}
					</li>
					<li>
						 {% placeholder sivusisalto3 %}
     						 {% block sivusisalto3%}{% endblock %}
					</li>
					
				</ul>
			</div>
		</div>
		<!-- end #sidebar -->
		<div style="clear: both; height:55px;">&nbsp;</div>
	</div>
	<!-- end #page -->

<div id="content">

</div>
<div id="footer">
	<p style="text-transform:capitalize">Copyright 2012 © Tomi Tapio. All rights reserved.</p>
</div>
<!-- end #footer -->


  </body>
</html>

rose/templates/base_ori.html
{% load menu_tags cache %}
{% load i18n cms_tags menu_tags%}
{% load cms_tags sekizai_tags %}
{% load sekizai_tags %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
      {% render_block "css" %}
{% addtoblock "css" %}
<link href="{{STATIC_URL}}css/style.css" rel="stylesheet" type="text/css"/>
<link href="{{STATIC_URL}}js/css/pepper-grinder/jquery-ui-1.8.23.custom.css" rel="stylesheet" type="text/css"/>
<link href="http://fonts.googleapis.com/css?family=Abel" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" media="all" href="{{STATIC_URL}}css/niceforms-default.css" />
{%endaddtoblock%} 
{% render_block "js" %}
  </head>
  <body>
      {% cms_toolbar %}
  
      
	{% addtoblock "js" %}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
   <script type="text/javascript" src="{{STATIC_URL}}js/js/jquery-ui-1.8.23.custom.min.js"></script>
   <script type="text/javascript" src="{{STATIC_URL}}js/js/jquery-ui-fi.js"></script>

 <script type="text/javascript" src="{{STATIC_URL}}js/js/jquery.dropotron-1.0.js"></script>
<script language="javascript" type="text/javascript" src="{{STATIC_URL}}js/js/niceforms.js"></script>
<script>
	$(function() {
		$( "#id_tarjoukset_viimeistaan" ).datepicker();
		$( "#id_haku_viimeistaan" ).datepicker();
	});
	</script>

{%endaddtoblock%} 
<div id ="wrapper">

	<div id="header-wrapper">

		<div id="header">
			<div id="logo">
				<h1><a href="#">BIDS</a></h1>
				<p>Chuck Norris loves bids.</p>
			</div>
		</div>
	
	</div>
	<!-- end #header -->
	<div id="menu-wrapper">
		<ul id="menu"><span>
			 {% show_menu 0 100 100 100 %}
			</span>
			
			<li><a href="#"><span>ketä ollaan</span></a></li>
			<li><a href="/tarjoukset" target="_self"><span>Jätä tarjouspyyntö!</span></a> </li>
			
			<li><a href="/tyopaikat/tyopaikat_haku" target="_self"><span>Avoimet työpaikat</span></a> </li>
			<li><a href="/tarjoukset/selaa"><span>Selaa tarjouspyyntöjä</span></a></li>
			<li><span>Yrityksille</span>
				<ul>
					<li class="first"> <a href="/accounts/signin/" target="_self">Kirjaudu</a>  </li>
					<li class="last"> <a href="/accounts/signup/" target="_self">Rekisteröidy</a>  </li>
					
					<li class="last"> <a href="#" target="_self">Miten homma toimii</a>  </li>
				</ul>
			</li>
		</ul>

		<script type="text/javascript">
			$('#menu').dropotron();
		</script>
	</div>
	<!-- end #menu -->
	<div id="splash"><img src="images/pics01.jpg" width="980" height="300" alt="" /></div>
	<div id="page">
		<div id="content">
			<div class="contentbg">
				<div class="post">
					<div class="entry">
						 {% placeholder content %}
      {% block content%}{% endblock %}
					</div>
				</div>
				
			</div>
		</div>
		<!-- end #content -->
		<div id="sidebar-bg">
			<div id="sidebar">
				<ul>
					<li>
						 {% placeholder sivusisalto %}
     						 {% block sivusisalto%}{% endblock %}
					</li>
					<li>
						 {% placeholder sivusisalto2 %}
     						 {% block sivusisalto2%}{% endblock %}
					</li>
					<li>
						 {% placeholder sivusisalto3 %}
     						 {% block sivusisalto3%}{% endblock %}
					</li>
					
				</ul>
			</div>
		</div>
		<!-- end #sidebar -->
		<div style="clear: both; height:55px;">&nbsp;</div>
	</div>
	<!-- end #page -->

<div id="content">

</div>
<div id="footer">
	<p style="text-transform:capitalize">Copyright 2012 © Tomi Tapio. All rights reserved.</p>
</div>
<!-- end #footer -->


  </body>
</html>

rose/templates/contacts.html
<html>
<head>
  <title>Contacts</title>
</head>
 
<body>
{% if message %}
  <b>{{ message }}</ b>
  <p />
{% endif %}
 
{% if contact_list %}
<table>
  {% for contact in contact_list %}
  <tr bgcolor='{% cycle FFFFFF,EEEEEE as rowcolor %}'>
    <td>{{ contact.name }}</td>
    <td><a href='{{ request.path }}?edit_id={{ contact.id }}'>Edit</a></td>
    <td><a href='{{ request.path }}?delete_id={{ contact.id }}'>Delete</a></td>
  </tr>
  {% endfor %}
</table>
<p />
{% endif %}
 
<form action='{{ request.path }}' method='POST'>
<input type='hidden' name='edit_id' value='{{ edit_id }}'>
<table>
{{ form }}
<tr>
  <td colspan=2 align=right>
    <input type=submit name='submit_action' value='{{ submit_action }}'>
  </td>
</tr>
</table>
</form>
 
{% ifnotequal submit_action 'Add' %}
  <p />
  <a href='{{ request.path }}'>Add New Contact</a>
{% endifnotequal %}
</html>

rose/templates/hello_plugin.html
<h1>Hello {% if request.user.is_authenticated %}{{ request.user.first_name }} {{ request.user.last_name}}{% else %}Guest{% endif %}</h1>

rose/templates/template.html
{% extends 'base.html' %}

rose/templates/template2.html
{% load menu_tags cache %}
{% load i18n cms_tags menu_tags%}
{% load cms_tags sekizai_tags %}
<html>
  <head>
      {% render_block "css" %}
{% addtoblock "css" %}
<link href="{{STATIC_URL}}css/style.css" rel="stylesheet" type="text/css"/>
{%endaddtoblock%} 
  </head>
  <body>
      {% cms_toolbar %}

      {% render_block "js" %}
<div id="header">
<div id="admin">
<a href="/admin" target="_blank">Kirjaudu järjestelmään</a> 
</div></div>
  <div id="navi">
					
             {% show_menu %}
            </div>
<div id="content">

      {% placeholder base_content %}
      {% block base_content%}{% endblock %}


      		
</div>
 
  </body>
</html>